api_version: "v1"
runtime: python39  # or your appropriate Python runtime version
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GOOGLE_CLOUD_PROJECT: even-electron-428800-b6
  GOOGLE_CLOUD_BUCKET: disease-approximation-data
  MANIFEST_FILE: data/compression_manifest_latest.json
  ENSEMBL_TO_GENE_FILE: data/ensembl_to_gene.csv
  